# Generated by Django 5.0.6 on 2024-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedZipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='uploads/zips/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
